### ISSUE TITLE
[TODO] 1주차 SQL과제

### ISSUE THREAD

**Issue by ParkYeoungJae** [ParkYeoungJae/Job-BootCamp--SQL-to-Dashboard#1]
w3schools.com 예시 database를 활용한 문제 해결

문제
- [x] Country 별로 ContactName이 ‘A’로 시작하는 Customer의 숫자를 세는 쿼리를 작성하세요
- [ ] Customer 별로 Order한 Product의 총 Quantity를 세는 쿼리를 작성하세요
- [ ] 년월별, Employee별로 Product를 몇 개씩 판매했는지를 표시하는 쿼리를 작성하세요

(join을 하기 위해 with 구문을 사용하실 필요는 없습니다.)
